version: "3.9"

services:
  redis:
    image: redis:7-alpine
    container_name: whatsapp_redis
    command: ["redis-server", "--save", "20", "1", "--loglevel", "warning"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

  backend:
    build: .
    container_name: whatsapp_backend
    depends_on:
      redis:
        condition: service_healthy
    env_file:
      - .env.local-cloudrun
    environment:
      # Point backend at the Redis container
      - REDIS_URL=${REDIS_URL:-redis://redis:6379}
      # Optional: tweak WS pub/sub and rate limits via env or .env file
      - ENABLE_WS_PUBSUB=${ENABLE_WS_PUBSUB:-1}
      - SEND_TEXT_PER_MIN=${SEND_TEXT_PER_MIN:-30}
      - SEND_MEDIA_PER_MIN=${SEND_MEDIA_PER_MIN:-15}
    ports:
      - "8080:8080"
    volumes:
      - ./media:/app/media
      - ./data:/app/data

volumes:
  redis_data:
    driver: local


