services:
  - type: web
    name: whatsapp-backend
    env: python
    plan: free
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "uvicorn backend.main:app --host 0.0.0.0 --port 10000 --loop uvloop --http httptools --proxy-headers --forwarded-allow-ips='*' --log-level ${LOG_LEVEL:-info}"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
    buildFilter:
      paths:
        - backend/**
    autoDeploy: true
    rootDir: .
